#v.0.1.0
[parser]
sourceDataPath="/Users/marcotusa/work/percona/Tech_Lead/Projects/Benchmarking_procedures/processed/ps_vs_my_8034_iron/sysbench/"



[render]
graphType="column"
destinationPath=""

[global]
testName=""
logLevel = "debug"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/tmp/sysbench_graph_creator.log"
performance = true
OS = "na"
