#v.1.4.4
[parser]
sourceDataPath=""


[render]
graphType="column"
graphPath=""

[global]
logLevel = "debug"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/tmp/sysbench_graph_creator.log"
performance = true
OS = "na"
