#v.0.1.0
[parser]
sourceDataPath=""



[render]
graphType="column"
destinationPath=""

[global]
testName=""
logLevel = "debug"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/tmp/sysbench_graph_creator.log"
performance = true
OS = "na"
