#v.0.1.0
[parser]
sourceDataPath="/Users/marcotusa/work/percona/Tech_Lead/Projects/Benchmarking_procedures/not_processed/sysbench"



[render]
graphType="column"
destinationPath=""

[global]
testName=""
logLevel = "info"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/tmp/sysbench_graph_creator.log"
performance = true
OS = "na"
