#v.0.1.0
[parser]
sourceDataPath="/Users/marcotusa/work/blogs/2024/sakila_where_are_you_going/sysbench/base/logs"
#sourceDataPath="/Users/marcotusa/work/percona/Tech_Lead/Projects/Benchmarking_procedures/for_report/PS_VS_MYS_8036_optimized/logs" #MY-PS-8034-BASE

#sourceDataPath="/Users/marcotusa/work/percona/Tech_Lead/Projects/Benchmarking_procedures/not_processed/sysbench/MY-PS-8034-NO-AHI"
filterOutliners = true
distanceLabel = "operations/s"


[render]
graphType="column"
destinationPath="/Users/marcotusa/work/blogs/2024/sakila_where_are_you_going/sysbench/base"
#destinationPath="/Users/marcotusa/work/blogs/2024/sakila_where_are_you_going/sysbench/base/logs"
csvDestinationPath=""
printStats=false
printData=true
convertChartsToCsv=true
printCharts=false

httpServerPort=8089
httpServerIp="localhost"
labels="operations/s,latencyPct95(μs)"
#labels="TotalTime,Events/s,operations/s,writes/s,reads/s,latencyPct95(μs)"
statslabels="operations/s,latencyPct95(μs)"
readSummaryLabel="reads/s"
writeSummaryLabel="writes/s"
#labels="TotalTime,RunningThreads,totalEvents,Events/s,Tot Operations,operations/s,tot reads,reads/s,Tot writes,writes/s,oterOps/s,latencyPct95(μs) ,Tot errors,errors/s,Tot reconnects,reconnects/s,Latency(ms) min, Latency(ms) max, Latency(ms) avg, Latency(ms) sum"
#//TODO start
showReads=true
showWrites=true
showPreWrite=true
shoPostWrite=true
filterTestBy=""
#//TODO end
chartHeight=400
chartWidth=800
printChartsFormat="jpeg"


[global]
testName="Comparing PS VS MySQL"
logLevel = "info"
logTarget = "stdout" #stdout | file
logFile = "/Users/marcotusa/tmp/sysbench_graph_creator.log"

[colors]
color=[
    "name=Percona;version=8.0;color=#0e1a53"
    ,"name=Percona;version=9.0;color=#117e1a"
    ,"name=Percona;version=8.4;color=#ff7e1a"
    ,"name=Percona;version=5.7;color=#f0b336"
    ,"name=MySQL;version=5.7;color=#bac0cd"
    ,"name=MySQL;version=8.0;color=#93c7ff"
    ,"name=MySQL;version=8.4;color=#f9a98a"
    ,"name=Maria;version=11.3;color=#f24500"
]
